### ISSUE TITLE
第一次警告，后续还能使用插件刷吗

### ISSUE THREAD

**Issue by Northxw** [ttglad/learning#109]
大概率是因为我更换了刷分设备，导致被第一次警告，完事儿让我进行了实名认证，不知道后续还能不能在同一台设备持续刷分的，有知道的伙伴或者亲测过的，麻烦告知以下，非常感谢

**Comment by kukukua** [comment]
我下午四点多也被警告了，不敢用了

**Comment by Northxw** [comment]
> 我下午四点多也被警告了，不敢用了

巧了，我也是四点多被警告了，实名完之后就没再刷分了，离谱.....

**Comment by 164724571** [comment]
同4月10日16:06分。

**Comment by 863683** [comment]
+1，还能继续用吗、、、

**Comment by haoakun** [comment]
一样 同问 10日下午3点54

**Comment by hwq1126** [comment]
我的也提示警告了，再用会不会被封号

**Comment by phyblog** [comment]
看样子都是下午使用的时候警告的，我一般都在早上9点-11点，或者就晚上8点之后，从来没有警告过

**Comment by AWIMF** [comment]
> 看样子都是下午使用的时候警告的，我一般都在早上9点-11点，或者就晚上8点之后，从来没有警告过

我都是早上八点开始运行的，还是下午15：33被警告了

**Comment by cnnjgz** [comment]
昨天下午提示：您的账号涉嫌违规刷分，已被系统封禁，期间无法积分

哎，这帮监控的人真是有精力，就这么强国

**Comment by cnnjgz** [comment]
> 警告几次封禁的？ &nbsp; 方明 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月22日(星期六) 上午7:59 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ttglad/learning] 第一次警告，后续还能使用插件刷吗 (Issue #109) 昨天下午提示：您的账号涉嫌违规刷分，已被系统封禁，期间无法积分 哎，这帮监控的人真是有精力，就这么强国 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

第一次提醒，强国app里面有处理提醒，说是3次后，就清零啥的

既然如此，以前还点击刷机，弄点积分，面子上过得去，现在卸载APP，随它去吧

**Comment by haoakun** [comment]
我现在被提醒两次了，第一次是用这个learning第二次是用的手机上的软件，看来现在的检测手段是看你文章阅读和完成时间是不是符合特定的时间规律，只要不象是正常人的阅读习惯就直接判定作弊

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月22日 9:04
收件人: ***@***.***>
抄送: Hao ***@***.***>; ***@***.***>
主题: Re: [ttglad/learning] 第一次警告，后续还能使用插件刷吗 (Issue #109)


警告几次封禁的？   方明 @.***
…
------------------ 原始邮件 ------------------ 发件人: @.>; 发送时间: 2023年4月22日(星期六) 上午7:59 收件人: @.>; 抄送: @.>; @.>; 主题: Re: [ttglad/learning] 第一次警告，后续还能使用插件刷吗 (Issue #109<https://github.com/ttglad/learning/issues/109>) 昨天下午提示：您的账号涉嫌违规刷分，已被系统封禁，期间无法积分 哎，这帮监控的人真是有精力，就这么强国 ― Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

第一次提醒，强国app里面有处理提醒，说是3次后，就清零啥的

既然如此，以前还点击刷机，弄点积分，面子上过得去，现在卸载APP，随它去吧

―
